# Generated by Django 5.0.3 on 2024-03-25 12:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WatchableMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=200)),
                ("GenreTags", models.TextField()),
                ("Downloaded", models.BooleanField(default=False)),
                ("Watched", models.BooleanField(default=True)),
                ("ImportDate", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "watchablemedia_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.watchablemedia",
                    ),
                ),
                ("Year", models.IntegerField()),
            ],
            bases=("media.watchablemedia",),
        ),
        migrations.CreateModel(
            name="TVShow",
            fields=[
                (
                    "watchablemedia_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.watchablemedia",
                    ),
                ),
                ("Length", models.IntegerField()),
                ("Progress", models.IntegerField()),
            ],
            bases=("media.watchablemedia",),
        ),
    ]
