# Generated by Django 5.0.3 on 2024-03-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=200)),
                ("GenreTags", models.TextField()),
                ("Downloaded", models.BooleanField(default=False)),
                ("InfoPage", models.CharField(max_length=200)),
                (
                    "Logo",
                    models.CharField(
                        default="https://upload.wikimedia.org/wikipedia/commons/c/c9/Icon_Video.png",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WatchableMedia",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.media",
                    ),
                ),
                ("Watched", models.BooleanField(default=True)),
                ("Duration", models.DurationField()),
            ],
            bases=("media.media",),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "watchablemedia_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.watchablemedia",
                    ),
                ),
                ("Author", models.CharField(max_length=50)),
            ],
            bases=("media.watchablemedia",),
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "watchablemedia_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.watchablemedia",
                    ),
                ),
                ("Year", models.IntegerField()),
            ],
            bases=("media.watchablemedia",),
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "watchablemedia_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.watchablemedia",
                    ),
                ),
                ("Show", models.CharField(max_length=50)),
            ],
            bases=("media.watchablemedia",),
        ),
        migrations.CreateModel(
            name="TVShow",
            fields=[
                (
                    "watchablemedia_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.watchablemedia",
                    ),
                ),
                ("Length", models.IntegerField()),
            ],
            bases=("media.watchablemedia",),
        ),
        migrations.CreateModel(
            name="Youtube",
            fields=[
                (
                    "watchablemedia_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.watchablemedia",
                    ),
                ),
                ("Creator", models.CharField(max_length=50)),
                ("Link", models.CharField(max_length=200)),
            ],
            bases=("media.watchablemedia",),
        ),
    ]
