# Generated by Django 5.0.3 on 2024-03-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchablemedia",
            name="AddedBy",
            field=models.CharField(default="mchaae01", max_length=200),
            preserve_default=False,
        ),
    ]
