# Generated by Django 5.0.3 on 2024-04-04 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_rename_genretags_media_genre_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="Show",
            new_name="Creator",
        ),
    ]
