# Generated by Django 5.0.3 on 2024-03-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_watchablemedia_addedby"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchablemedia",
            name="WikiPage",
            field=models.CharField(default="Temp", max_length=200),
            preserve_default=False,
        ),
    ]
