# Generated by Django 5.0.3 on 2024-04-11 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0003_rename_show_podcast_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comic",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.media",
                    ),
                ),
                ("Company", models.CharField(max_length=50)),
                ("Character", models.CharField(max_length=50)),
                ("PageLength", models.IntegerField(default=0)),
            ],
            bases=("media.media",),
        ),
        migrations.CreateModel(
            name="Novel",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.media",
                    ),
                ),
                ("Author", models.CharField(max_length=50)),
                ("PageLength", models.IntegerField(default=0)),
            ],
            bases=("media.media",),
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
