# Generated by Django 5.0.3 on 2024-04-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0005_media_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="Read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="novel",
            name="Read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="watchablemedia",
            name="Watched",
            field=models.BooleanField(default=False),
        ),
    ]
