# Generated by Django 5.1 on 2024-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0006_comic_read_novel_read_alter_watchablemedia_watched"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="Series_End",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="Series_Start",
            field=models.IntegerField(default=-1),
        ),
    ]
