# Generated by Django 5.1 on 2024-09-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0007_tvshow_series_end_tvshow_series_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvshow",
            name="Series_End",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="Series_Start",
            field=models.DateField(),
        ),
    ]
