# Generated by Django 5.1 on 2024-09-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0012_rename_albums_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="Rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3), # type: ignore
        ),
    ]
