# Generated by Django 5.0.3 on 2024-04-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Institution", models.TextField()),
                ("Qualification", models.TextField()),
                ("Qualification_Level", models.TextField()),
                ("Start_Year", models.IntegerField(default=2001)),
                ("End_Year", models.IntegerField(default=2024)),
            ],
        ),
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Employer", models.TextField()),
                ("Job_Title", models.TextField()),
                ("Skills_Gained", models.TextField()),
                ("Responsibilities", models.TextField()),
                ("Start_Year", models.IntegerField(default=2001)),
                ("End_Year", models.IntegerField(default=2024)),
            ],
        ),
    ]
