# Generated by Django 5.0.3 on 2024-04-23 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0003_programminglanguage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProgrammingLanguage",
            new_name="SkillsAndTools",
        ),
    ]
