# Generated by Django 5.0.3 on 2024-04-23 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0004_rename_programminglanguage_skillsandtools"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skillsandtools",
            old_name="LanguageName",
            new_name="Name",
        ),
    ]
