# Generated by Django 5.0.3 on 2024-04-23 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0006_skillsandtools_islang"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skillsandtools",
            old_name="IsLang",
            new_name="Is_a_Language",
        ),
    ]
