# Generated by Django 5.0.3 on 2024-04-24 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0009_skillsandtools_skill_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillsandtools",
            name="Is_a_Language",
        ),
        migrations.RemoveField(
            model_name="skillsandtools",
            name="Is_a_Program",
        ),
    ]
