# Generated by Django 5.0.3 on 2024-04-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0010_remove_skillsandtools_is_a_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillsandtools",
            name="Proficiency",
            field=models.TextField(
                choices=[
                    ("Proficient", "Proficient"),
                    ("Experienced", "Experienced"),
                    ("Comfortable", "Comfortable"),
                    ("Familiar", "Familiar"),
                    ("Newbie", "Beginner"),
                    ("Never Used", "Never Used"),
                ]
            ),
        ),
    ]
